# Use an official lightweight Python image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install OS-level dependencies for lxml/beautifulsoup
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libxml2-dev \
    libxslt1-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements first for layer caching
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Catalog.json must exist at build time (generated by scraper.py locally
# and committed to the repo — NOT re-scraped at runtime).
# The COPY . . above picks it up.

# Expose the FastAPI port
EXPOSE 8000

# Start the server
# Using 1 worker for free-tier memory constraints; increase for production.\
CMD uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000} --workers 1
